<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- ROS Control plugin -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <robotNamespace>/</robotNamespace>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${base_width}</wheelSeparation>
      <legacyMode>false</legacyMode>
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>true</publishWheelJointState>
      <max_wheel_torque>10</max_wheel_torque>
      <wheelAcceleration>0.5</wheelAcceleration>
      <max_wheel_acceleration>0.5</max_wheel_acceleration>
      <wheelTorque>10</wheelTorque>
      <updateRate>50</updateRate>
      <max_velocity>0.5</max_velocity>
    </plugin>
  </gazebo>

  <gazebo reference="laser_link">
    <sensor type="ray" name="rplidar">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>6.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_rplidar_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <material name="orange">
    <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp  value="10000000.0"/>
    <kd  value="100.0"/>
    <maxVel>0.0</maxVel>
    <minDepth>0.001</minDepth>
  </gazebo>

  <gazebo reference="caster_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp  value="10000000.0" />
    <kd  value="1.0" />
    <material>Gazebo/Orange</material>
  </gazebo>
  <gazebo reference="right_wheel">
    <mu1 value="1.5"/>
    <mu2 value="1.5"/>
    <kp  value="10000000.0" />
    <kd  value="1.0" />
    <fdir1 value="1 0 0"/>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="left_wheel">
    <mu1 value="1.5"/>
    <mu2 value="1.5"/>
    <kp  value="10000000.0" />
    <kd  value="1.0" />
    <fdir1 value="1 0 0"/>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="left_wall">
    <material>Gazebo/Grey</material>
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp  value="10000000.0"/>
    <kd  value="100.0"/>
    <maxVel>0.0</maxVel>
    <minDepth>0.001</minDepth>
  </gazebo>
  <gazebo reference="right_wall">
    <material>Gazebo/Grey</material>
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp  value="10000000.0"/>
    <kd  value="100.0"/>
    <maxVel>0.0</maxVel>
    <minDepth>0.001</minDepth>
  </gazebo>

</robot>