<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Lidar cylinder -->
  <link name="lidar_base_cylinder">
    <visual>
      <geometry>
        <cylinder length="${lidar_cylinder_height}" radius="0.02"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lidar_cylinder_height}" radius="0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="base_to_cylinder" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_base_cylinder"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
  </joint>
  <!-- Lidar Link -->
  <link name="laser_link">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
        iyy="0.00001" iyz="0.0"
        izz="0.00001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- LiDAR Joint -->
  <joint name="laser_joint" type="fixed">
    <parent link="lidar_base_cylinder"/>
    <child link="laser_link"/>
    <origin xyz="${lidar_mount_x} ${lidar_mount_y} ${lidar_cylinder_height - base_height}" rpy="0 0 0"/>
  </joint>
</robot>