<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${2 * wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1"/>
        <inertia ixx="0.0007" ixy="0" ixz="0" iyy="0.0007" iyz="0" izz="0.0007"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y * (base_width/2 + wheel_radius/2)} 0" rpy="${pi/2} 0 0"/>  <!-- Corrected RPY and Z offset -->
      <axis xyz="0 0 -1"/>
      <joint_properties damping="0.5" friction="0.5"/>
    </joint>
  </xacro:macro>

  <!-- Caster Wheel Macro -->
  <xacro:macro name="caster_wheel">
    <link name="caster_wheel">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <inertia ixx="0.00018" ixy="0" ixz="0" iyy="0.00018" iyz="0" izz="0.00018"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </inertial>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_wheel"/>
      <origin xyz="${base_length/3.3} 0 ${-caster_radius}" rpy="0 0 0"/>  <!-- Corrected Z offset for caster wheel -->
      <dynamics damping="0.01"/>
    </joint>
  </xacro:macro>

  <!-- Arm Macro -->
  <xacro:macro name="arm" params="prefix side_mult">
    <link name="${prefix}_arm">
      <visual>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_length}"/>
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.25"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${prefix}_arm_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_arm"/>
      <origin xyz="${base_length/2} ${side_mult * (base_width /2 - 0.005)} 0.04"/>  <!-- Corrected Z offset for arm joint -->
      <axis xyz="0 1 0"/>
      <!-- <limit lower="${-arm_length/2}" upper="${arm_length/2}" effort="100" velocity="1"/>  --><!-- Adjusted limits for arm movement -->
    </joint>

    <!-- Gripper -->
    <link name="${prefix}_gripper">
      <visual>
        <geometry>
          <box size="${arm_length} 0.02 0.08"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${arm_length} 0.02 0.08"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.00005"/>
      </inertial>
    </link>

    <joint name="${prefix}_gripper_joint" type="fixed">
      <parent link="${prefix}_arm"/>
      <child link="${prefix}_gripper"/>
      <origin xyz="${arm_length/2} 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="guide_wall" params="side prefix">
    <link name="${prefix}_wall">
      <visual>
        <geometry>
          <box size="${wall_length} ${wall_thickness} ${wall_height}"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${wall_length} ${wall_thickness} ${wall_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.003"/>
      </inertial>
   </link>
   
   <joint name="${prefix}_wall_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wall"/>
      <origin xyz="${base_length/2 + wall_length/2} ${side * (base_width/2 + wall_thickness/2)} ${wall_height/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

</robot>