<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} 0" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>


  <!-- Caster Wheel Macro -->
  <xacro:macro name="caster_wheel">
    <link name="caster_wheel">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_wheel"/>
      <origin xyz="${base_length/2 - caster_radius} 0 -${caster_radius}"/>
    </joint>
  </xacro:macro>

  <!-- Arm Macro -->
  <xacro:macro name="arm" params="prefix side_mult">
    <link name="${prefix}_arm">
      <visual>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_length}"/>
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${prefix}_arm_joint" type="prismatic">
      <parent link="base_link"/>
      <child link="${prefix}_arm"/>
      <origin xyz="${base_length/2} ${side_mult * 0.1} ${base_height/2}"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.05" upper="0.05" effort="100" velocity="1"/>
    </joint>

    <!-- Gripper -->
    <link name="${prefix}_gripper">
      <visual>
        <geometry>
          <box size="${arm_length} 0.05 0.05"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${arm_length} 0.05 0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.00005"/>
      </inertial>
    </link>

    <joint name="${prefix}_gripper_joint" type="fixed">
      <parent link="${prefix}_arm"/>
      <child link="${prefix}_gripper"/>
      <origin xyz="${arm_length/2} 0 0"/>
    </joint>
  </xacro:macro>
</robot>