<?xml version="1.0"?>
<!-- three_wheeled_robot.xacro -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="three_wheeled_robot">

  <!-- Include property definitions -->
  <xacro:include filename="$(find pde4430_coursework2)/urdf/properties.xacro" />

  <!-- Include robot macros -->
  <xacro:include filename="$(find pde4430_coursework2)/urdf/macros.xacro" />

  <!-- Include Gazebo configurations -->
  <xacro:include filename="$(find pde4430_coursework2)/urdf/gazebo.xacro" />

  <!-- Base Link -->
  <link name="base_link">
    <origin xyz="0.2 0.1 ${base_height/2}" rpy="0 0 0"/>
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height/2}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.6"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>

  <xacro:caster_wheel />

  <xacro:wheel prefix="left" x="${-base_length/3}" y="1"/>
  <xacro:wheel prefix="right" x="${-base_length/3}" y="-1"/>

  <!-- <xacro:arm prefix="left" side_mult="1"/>
  <xacro:arm prefix="right" side_mult="-1"/> -->

  <xacro:guide_wall prefix="left" side="1"/>
  <xacro:guide_wall prefix="right" side="-1"/>
</robot>