<?xml version="1.0"?>
<!-- three_wheeled_robot.xacro -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="three_wheeled_robot">

  <!-- Include property definitions -->
  <xacro:include filename="$(find pde4430_coursework2)/urdf/properties.xacro" />

  <!-- Include robot macros -->
  <xacro:include filename="$(find pde4430_coursework2)/urdf/macros.xacro" />

  <!-- Include Gazebo configurations -->
  <xacro:include filename="$(find pde4430_coursework2)/urdf/gazebo.xacro" />

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.0833" ixy="0" ixz="0" iyy="0.0833" iyz="0" izz="0.1667"/>
    </inertial>
  </link>

  <!-- Add wheels -->
  <!-- <xacro:wheel prefix="left" x="0" y="${base_width/2}"/>
  <xacro:wheel prefix="right" x="0" y="-${base_width/2}"/> -->

  <xacro:wheel prefix="left" x="${-base_length/2 + wheel_radius}" y="${base_width/2 + wheel_radius/4}"/>
  <xacro:wheel prefix="right" x="${-base_length/2 + wheel_radius}" y="${-base_width/2 - wheel_radius/4}"/>
  <!-- Add caster wheel -->
  <xacro:caster_wheel />

  <!-- Add arms -->
  <xacro:arm prefix="left" side_mult="1"/>
  <xacro:arm prefix="right" side_mult="-1"/>


</robot>