# Joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Wheel controllers
left_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Arm controllers
left_arm_controller:
  type: effort_controllers/JointPositionController
  joint: left_arm_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_arm_controller:
  type: effort_controllers/JointPositionController
  joint: right_arm_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}