diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ["left_wheel_joint"]
  right_wheel: ["right_wheel_joint"]
  publish_rate: 50
  wheel_separation: 0.5
  wheel_radius: 0.15
  cmd_vel_timeout: 0.25
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  publish_tf: true